adminapp/urls.py
from django.urls import path
from adminapp import views as admin_views

app_name = 'adminapp'

urlpatterns = [

    path('users/create/', admin_views.user_create, name='user_create'),
    path('users/', admin_views.UserListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', admin_views.user_update, name='user_update'),
    path('users/delete/<int:pk>/', admin_views.user_delete, name='user_delete'),

    path('categories/create/', admin_views.category_create, name='category_create'),
    path('categories/', admin_views.categories, name='category_list'),
    path('categories/update/<int:pk>/', admin_views.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', admin_views.category_delete, name='category_delete'),

    path('products/create/<int:pk>/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', admin_views.ProductsListView.as_view(), name='product_list'),
    path('products/update/<int:pk>/', admin_views.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', admin_views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/detail/<int:pk>/', admin_views.ProductDetailView.as_view(), name='product_detail'),

]

authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')

]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from django import forms

from mainapp.models import Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductEditForm(forms.ModelForm):

    class Meta:
        model = Product
        # fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from adminapp.forms import ShopUserAdminEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class AccessMixin:

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_list'))

    else:
        user_form = ShopUserAdminEditForm()

    context = {
        'form': user_form,
    }
    return render(request, 'adminapp/user_form.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     context = {
#         'object_list': ShopUser.objects.all().order_by('-is_active'),
#     }
#     return render(request, 'adminapp/users.html', context)


class UserListView(AccessMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    current_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=current_user)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_list'))

    else:
        user_form = ShopUserAdminEditForm(instance=current_user)

    context = {
        'form': user_form,
    }
    return render(request, 'adminapp/user_form.html' , context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    current_user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        if current_user.is_active:
            current_user.is_active = False
        else:
            current_user.is_active = True
        current_user.save()
        return HttpResponseRedirect(reverse('adminapp:user_list'))

    context = {
        'object': current_user,
    }
    return render(request, 'adminapp/user_delete.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    context = {

    }
    return render(request, '', context)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    context = {
        'object_list': ProductCategory.objects.all().order_by('-is_active')
    }
    return render(request, 'adminapp/categories.html', context)


@user_passes_test(lambda u: u.is_superuser)
def category_update(request):
    context = {

    }
    return render(request, '', context)


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request):
    context = {

    }
    return render(request, '', context)


# @user_passes_test(lambda u: u.is_superuser)
# def product_create(request):
#     context = {
#
#     }
#     return render(request, '', context)


class ProductCreateView(AccessMixin, CreateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductEditForm

    def get_success_url(self):
        return reverse('adminapp:product_list', args=[self.kwargs['pk']])

# @user_passes_test(lambda u: u.is_superuser)
# def products(request, pk):
#     context = {
#         'category': get_object_or_404(ProductCategory, pk=pk),
#         'object_list': Product.objects.filter(category__pk=pk).order_by('-is_active'),
#     }
#     return render(request, 'adminapp/products.html', context)


class ProductsListView(AccessMixin, ListView):
    model = Product
    template_name = 'adminapp/products.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['category'] = get_object_or_404(ProductCategory, pk=self.kwargs.get('pk'))
        return context_data

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs.get('pk'))


# @user_passes_test(lambda u: u.is_superuser)
# def product_update(request):
#     context = {
#
#     }
#     return render(request, '', context)

class ProductUpdateView(AccessMixin, CreateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductEditForm

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


# @user_passes_test(lambda u: u.is_superuser)
# def product_delete(request):
#     context = {
#
#     }
#     return render(request, '', context)

class ProductDeleteView(AccessMixin, DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


# @user_passes_test(lambda u: u.is_superuser)
# def product_detail(request):
#     context = {
#
#     }
#     return render(request, '', context)

class ProductDetailView(AccessMixin, DetailView):
    model = Product
    template_name = 'adminapp/product_detail.html'

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/basket.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
    <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
    </div>
    <span>
        {% if basket %}
            {{ basket.0.total_cost|floatformat:0 }} руб <br>
            {{ basket.0.total_quantity }} шт
        {% endif %}
    </span>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="categories_list">
    <button class="new_category">
        <a href={% url 'adminapp:category_create' %}>
        новая категория
        </a>
    </button>

    {% for object in object_list %}
    <div class="category_record">
        <div class="category_name">
            {{ object.name|title }}
        </div>
        <div class="category_actions">
            <button>
                <a href={% url 'adminapp:product_list' object.pk %}>
                товары категории
                </a>
            </button>
            <button>
                <a href={% url 'adminapp:category_update' object.pk %}>
                редактировать
                </a>
            </button>
            <button>
                <a href={% url 'adminapp:category_delete' object.pk %}>
                удалить
                </a>
            </button>
        </div>
        <div class="category_desc">
            {{ object.description|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="">
        {% if object.is_active %}
            Уверены, что хотите удалить продукт {{ object.get_full_name }}?
        {% else %}
            Уверены, что хотите восстановить продукт?
        {% endif %}
    </div>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Уверен">
    </form>
    <a href="{% url 'adminapp:product_list' object.category.pk %}" class="btn btn-success">Нет</a>
{% endblock %}

adminapp/templates/adminapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} /
            {{ object.name|title }}</strong>
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
             alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href="{% url 'adminapp:product_update' object.pk %}">редактировать</a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'adminapp:product_delete' object.pk %}">удалить</a>
                </button>
            </p>
            <p>
                <button>
                <a href="{% url 'adminapp:product_list' object.category.pk %}">назад</a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <br><br>
            <b>подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Сохранить" class="btn btn-primary">
</form>
<button class="btn btn-warning">
    Назад
</button>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<div class="products_list">
    <button class="new_product">
        <a href="{% url 'adminapp:product_create' category.pk %}">
            новый продукт
        </a>
    </button>

    {% for object in object_list %}
    <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img
                src="{{ object.image|media_for_products }}"
                alt="{{ object.name }}">
        <div class="product_name">
            {{ object.name|title }}
        </div>
        <div class="product_actions">
            <button>
                <a href="{% url 'adminapp:product_detail' object.pk %}">
                    подробнее
                </a>
            </button>
            <button>
                <a href="{% url 'adminapp:product_update' object.pk %}">
                    редактировать
                </a>
            </button>
            <button>
                <a href="{% url 'adminapp:product_delete' object.pk %}">
                    удалить
                </a>
            </button>
        </div>
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
            {{ object.short_desc|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="">
        {% if object.is_active %}
            Уверены, что хотите удалить пользователя {{ object.get_full_name }}?
        {% else %}
            Уверены, что хотите восстановить пользователя?
        {% endif %}
    </div>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Уверен">
    </form>
    <a href="{% url 'adminapp:user_list' %}" class="btn btn-success">Нет</a>
{% endblock %}

adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Сохранить" class="btn btn-primary">
</form>
<button class="btn btn-warning">
    Назад
</button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<div class="users_list">
    <button class="new_user">
        <a href="{% url 'adminapp:user_create' %}">
            новый пользователь
        </a>
    </button>
    {% for object in object_list %}
    <div
            class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img
                src="{{ object.avatar|media_for_users }}"
                alt="{{ object.username }}">
        <div class="user_role">
            {% if object.is_superuser %}
                администратор
            {% else %}
                пользователь
            {% endif %}
            <button>
                <a href="{% url 'adminapp:user_update' object.pk %}">
                    редактировать
                </a>
            </button>
            <button>
                <a href="{% url 'adminapp:user_delete' object.pk %}">
                    {% if object.is_active %}
                        удалить
                    {% else %}
                        восстановить
                    {% endif %}
                </a>
            </button>
        </div>
        <div class="user_name">
            <p><strong>{{ object.username }}</strong></p>
            <p>
                {% if object.first_name %}
                <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
            <p>{{ object.last_name|title }}</p>
            {% endif %}
            {% endif %}
            </p>
        </div>
        <div class="user_age">
            age:<br>
            {{ object.age }} лет
        </div>
        <div class="user_email">
            email:<br>
            {{ object.email }}
        </div>
        <div class="user_lastlogin">
            logged:<br>
            {{ object.last_login }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}