authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')

]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='basket'),
    path('add/<int:pk>/', basketapp.add, name='add'),
    path('remove/<int:pk>/', basketapp.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit'),

]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/<int:page>/', mainapp.products, name='category_page'),
    path('product/<int:pk>/', mainapp.product, name='product'),

]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория продукта'
        verbose_name_plural = 'категории продукта'
        ordering = ['name']


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=255, verbose_name='краткое описание', blank=True)
    description = models.TextField(verbose_name='описание', blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['name']

mainapp/views.py
import random

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def get_hot_product():
    return random.sample(list(Product.objects.all()), 1)[0]


def get_same_products(hot_product):
    product_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return product_list


def index(request):
    context = {
        'title': 'Главная',
        'products': Product.objects.all()[:4],
    }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    context = {
        'title': 'Контакты',
    }
    return render(request, 'mainapp/contact.html', context)


def products(request, pk=None, page=1):
    links_menu = ProductCategory.objects.all()
    if pk is not None:
        if pk == 0:
            # products_list = Product.objects.all().order_by('?')[:4]
            products_list = Product.objects.all()
            category_item = {
                'name': 'все',
                'pk': 0,
            }
        else:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)

        # page = request.GET.get('p', 1)
        paginator = Paginator(products_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'links_menu': links_menu,
            'title': 'Продукты',
            'category': category_item,
            'products': products_paginator,
        }
        return render(request, 'mainapp/products_list.html', context=context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    context = {
        'links_menu': links_menu,
        'title': 'Продукты',
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', context=context)


def product(request, pk):

    context = {
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
    }

    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{{title|title}}{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js%}
    {% endblock %}
</head>
<body>
{% block menu %}
{% endblock %}

{% block content %}
{% endblock %}

<div class="clr"></div>

</div>

{% block footer %}
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB {% now 'Y' %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
<!--{% load static %}-->
{% block menu %}
<div class="hero">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
    <h1>наши контакты</h1>
</div>
{% endblock %}

{% block content %}
<div class="location">
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
<div class="slider">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="featured">
    <div class="featured-menu">
        <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
    </div>
    <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
    <div class="clearfix">
    </div>
    <div class="tab-content">
        {% for product in products %}
        <div class="block">
            <a href="{% url 'mainapp:product' product.pk %}"><img src="/media/{{ product.image }}" alt="">
                <div class="text">
                    <img src="/static/img/icon-hover.png" alt="img">
                    <h4>{{ product.name }}</h4>
                    <p>{{ product.short_desc }} </p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product.name }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> {{ product.price|floatformat:2 }} <span>руб</span></p>
            <a href="{% url 'basket:add' product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>{{ product.short_desc }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ hot_product.image }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ hot_product.name }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> {{ hot_product.price|floatformat:2 }} <span>руб</span></p>
            <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>{{ hot_product.short_desc }}</p>
            </div>
        </div>
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for product in same_products %}
            <div class="block">
                <a href="#"><img src="/media/{{ product.image }}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.category.name }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
        <div class="title clearfix">
            <h2>
                Категория: "{{ category.name|capfirst }}"
            </h2>
        </div>
        <div class="pagination">
            {% if products.has_previous %}
                <a href="{% url 'mainapp:category_page' category.pk products.previous_page_number %}"><<</a>
            {% endif %}
            {{ products.number }} / {{ products.paginator.num_pages }}
            {% if products.has_next %}
                <a href="{% url 'mainapp:category_page' category.pk products.next_page_number %}">>></a>
<!--                <a href="{% url 'mainapp:category' category.pk %}?p={{ products.next_page_number }}">>></a>-->
            {% endif %}
        </div>
        <div class="category-products clearfix">

            {% for product in products %}
            <div class="block">
                <a href="{% url 'mainapp:product' product.pk %}">
                    <img src="/media/{{ product.image }}" alt="product">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.description }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}

        </div>
    </div>
</div>

<div class="clr"></div>

{% endblock %}